version: '3.6'
services:
  flowable-modeler-app:
    image: flowable/flowable-modeler:latest
    depends_on:
      - flowable-db
    environment:
      - SERVER_PORT=8888
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM-URL=http://host.docker.internal:8090/flowable-idm
      - FLOWABLE_COMMON_APP_IDM-ADMIN_USER=admin
      - FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD=test
    ports:
      - 8888:8888
    entrypoint: ["./wait-for-something.sh", "flowable-db", "5432", "PostgreSQL", "java -jar /app.war"]

  flowable-idm-app:
    image: flowable/flowable-idm:latest
    depends_on:
      - flowable-db
    environment:
      - SERVER_PORT=8090
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_REST_APP_ADMIN_USER-ID=admin
      - FLOWABLE_REST_APP_ADMIN_PASSWORD=test
    ports:
      - 8090:8090
    entrypoint: ["./wait-for-something.sh", "flowable-db", "5432", "PostgreSQL", "java -jar /app.war"]

  flowable-db:
    image: postgres:9.6-alpine
    container_name: flowable-postgres
    environment:
      - POSTGRES_PASSWORD=flowable
      - POSTGRES_USER=flowable
      - POSTGRES_DB=flowable
    ports:
      - 5433:5432
    command: postgres